using System.Text;

namespace Sed.Formats.Cogs;

/// <summary>Player weapons the generated master COG can grant (JK inventory bins).</summary>
[Flags]
public enum JkWeapons
{
    None = 0,
    Briar = 1 << 0,
    StormtrooperRifle = 1 << 1,
    ThermalDetonators = 1 << 2,
    Crossbow = 1 << 3,
    Repeater = 1 << 4,
    Railgun = 1 << 5,
    SequencerCharges = 1 << 6,
    ConcussionRifle = 1 << 7,
    Lightsaber = 1 << 8,
}

/// <summary>Inputs for the generated level master COG.</summary>
public sealed class MasterCogOptions
{
    /// <summary>Index of the level's first goal string in `cogstrings.uni`.</summary>
    public int GoalBase { get; init; }

    /// <summary>Goal descriptions, in order; one <c>SetGoalFlags</c> call each.</summary>
    public IReadOnlyList<string> Goals { get; init; } = Array.Empty<string>();

    public JkWeapons Weapons { get; init; } = JkWeapons.None;

    /// <summary>Starting Force rank (inventory bin 20).</summary>
    public int ForceRank { get; init; }
}

/// <summary>
/// Generates a level master COG (`U_COGGEN.PAS`) — the script that registers
/// itself as the level's master, initialises the player's goals, hands out
/// starting weapons and ammunition, and sets the Force rank on a timer.
///
/// Ammunition follows the original's rules rather than being granted blindly:
/// energy only when a weapon that consumes it is given, power only for the
/// power-based weapons, rail charges only with the railgun.
/// </summary>
public static class MasterCogGenerator
{
    public static string Generate(MasterCogOptions options, string version = "SED .NET")
    {
        var w = options.Weapons;
        var sb = new StringBuilder();

        sb.AppendLine("#Level master COG");
        sb.AppendLine($"#Generated by {version}");
        sb.AppendLine();
        sb.AppendLine("symbols");
        sb.AppendLine("message   startup");
        sb.AppendLine("message   timer");
        sb.AppendLine("int       player    local");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("code");
        sb.AppendLine();
        sb.AppendLine("startup:");
        sb.AppendLine("  // Register COG as master COG");
        sb.AppendLine("  SetMasterCOG(GetSelfCOG());");
        sb.AppendLine("  player = GetLocalPlayerThing();");
        sb.AppendLine("  // Initialise Goals");
        sb.AppendLine($"  SetInv(player, 99, {options.GoalBase});");

        for (int i = 0; i < options.Goals.Count; i++)
            sb.AppendLine($"  SetGoalFlags(player, {i}, 1);");

        sb.AppendLine("  // Give player weapons and ammo");
        sb.AppendLine("  SetInv(player, 1, 1);   // fists");

        Weapon(sb, w, JkWeapons.Briar, 2, 1, "briar");
        Weapon(sb, w, JkWeapons.StormtrooperRifle, 3, 1, "ST Rifle");
        Weapon(sb, w, JkWeapons.ThermalDetonators, 4, 1, "TD");
        Weapon(sb, w, JkWeapons.Crossbow, 5, 1, "Crossbow");
        Weapon(sb, w, JkWeapons.Repeater, 6, 1, "Repeater");
        Weapon(sb, w, JkWeapons.Railgun, 7, 1, "Railgun");
        Weapon(sb, w, JkWeapons.SequencerCharges, 8, 10, "Sequencer charges");
        Weapon(sb, w, JkWeapons.ConcussionRifle, 9, 1, "Concussion Rifle");
        Weapon(sb, w, JkWeapons.Lightsaber, 10, 1, "Lightsaber");

        // Ammunition only for the weapons that actually consume it.
        if (w.HasFlag(JkWeapons.Briar) || w.HasFlag(JkWeapons.StormtrooperRifle))
            sb.AppendLine("  SetInv(player, 11, 100);   // Energy");
        if (w.HasFlag(JkWeapons.Crossbow) || w.HasFlag(JkWeapons.Repeater) || w.HasFlag(JkWeapons.ConcussionRifle))
            sb.AppendLine("  SetInv(player, 12, 100);   // Power");
        if (w.HasFlag(JkWeapons.Railgun))
            sb.AppendLine("  SetInv(player, 15, 10);   // Railcharges");

        sb.AppendLine("  // Initialize weapon.");
        sb.AppendLine("  SetFireWait(player, -1);");
        sb.AppendLine("  SetMountWait(player, 0);");
        sb.AppendLine("  SetCurInvWeapon(player, 0);");
        sb.AppendLine("  SelectWeapon(player, AutoSelectWeapon(player, 1));");
        sb.AppendLine();
        sb.AppendLine("  SetTimer(15);");
        sb.AppendLine();
        sb.AppendLine("timer:");
        sb.AppendLine("  // Force ranking");
        sb.AppendLine($"  SetInv(player, 20, {options.ForceRank});");
        sb.AppendLine("  SetInv(player, 14, 4*50);");
        sb.AppendLine();
        sb.AppendLine("  jkSyncForcePowers();");
        sb.AppendLine("  Return;");
        sb.AppendLine();
        sb.AppendLine("end");

        return sb.ToString();
    }

    /// <summary>The `GOAL_nnnnn` key a goal at this offset occupies in cogstrings.uni.</summary>
    public static string GoalKey(int goalBase, int index) => $"GOAL_{goalBase + index:D5}";

    private static void Weapon(StringBuilder sb, JkWeapons have, JkWeapons flag,
        int bin, int count, string label)
    {
        if (have.HasFlag(flag)) sb.AppendLine($"  SetInv(player, {bin}, {count});   // {label}");
    }
}
